Project Filmorate v0.2.0
KosSpb/java-filmorate pull request #4
Opened 2023-04-06 17:25 UTC by KosSpb

2023-04-07 22:04 UTC, alexache requested changes

2023-04-07 22:04 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Set<Integer> friends = new HashSet<>();
(опционально) пожалуй, к этому моменту уже можно бы перейти на Long у id

2023-04-08 19:02 UTC, KosSpb commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -        log.info("createFilm: film \"{}\" with id {} was created.", film.getName(), film.getId());
Исправлено

2023-04-08 19:02 UTC, KosSpb commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!userStorage.getUsersList().contains(userStorage.getUserById(userId))) {
Исправлено

2023-04-08 19:02 UTC, KosSpb commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Set<Integer> friends = new HashSet<>();
Исправлено

2023-04-09 08:20 UTC, alexache approved these changes

2023-04-09 08:20 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!userStorage.getUsersIds().contains(userId)) {
Представь, что у тебя миллион пользователей, как думаешь, что будет быстрее перебор миллиона пользователей в поисках того самого, или получение из мапы по ключу=айди?

2023-04-09 08:20 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getUsersIds().contains(friendId)) {
И здесь похожий вопрос

2023-04-15 20:37 UTC, merged