Add database
KosSpb/java-filmorate pull request #6
Opened 2023-04-24 08:43 UTC by KosSpb

Смена хранилища InMemory на базу данных.

2023-04-24 20:40 UTC, alexache requested changes
Так же не хватает файла диаграммы со схемой базы данных и ссылкой из ридми

2023-04-24 20:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return filmStorage.updateFilm(film).get();
Получается 2 раза вызывается filmStorage.update? Для чего?

2023-04-24 20:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilmById(id).isPresent()) {
И тут 2 раза вызывается getFilmById? В целом более удобно пользоваться подходом:
Film film = filmStorage.getFilmById().orElseThrow(() -> new NotFoundException());

2023-04-24 20:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getFilmById(id).get();
Опять повторный вызов базы

2023-04-24 20:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FriendshipService.java
> +        return userStorage.getUserById(id).get();
Опять повторный вызов базы?

2023-04-24 20:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                jdbcTemplate.update(sqlQueryInsGenres, filmId, genre.getId());
Запросы к базе в цикле - очень плохо, лучше делать батч операцию

2023-04-24 20:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        if (film.getGenres().size() > 0) {
Дублирование кода с прошлым методом, лучше вынести в отдельный метод

2023-04-24 20:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        return getFilmById(film.getId());
Зачем делается гет запрос?

2023-04-24 20:40 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                .genres(new LinkedHashSet<>(genresOfFilm(resultSet.getLong("film_id"))))
Нельзя делать запросы к базе в цикле, это нужно выносить отдельно и получать по списку фильмов или по единичному фильму

2023-04-25 13:26 UTC, KosSpb commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return filmStorage.updateFilm(film).get();
Исправлено. 

По поводу файла диаграммы. Я не знал как лучше поступить и создал отдельную ветку для промежуточного ТЗ, и в ней добавил диаграмму и ридми. Перезалью их тогда, чтобы в этой ветке были.

2023-04-25 13:31 UTC, KosSpb commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilmById(id).isPresent()) {
Исправлено.

2023-04-25 13:40 UTC, KosSpb commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getFilmById(id).get();
Исправлено.

2023-04-25 13:49 UTC, KosSpb commented on src/main/java/ru/yandex/practicum/filmorate/service/FriendshipService.java
> +        return userStorage.getUserById(id).get();
Исправлено.

2023-04-25 20:56 UTC, KosSpb commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        return getFilmById(film.getId());
Убрал. Были проблемы с порядком жанров при десериализации из JSON. Поэтому заново собирал фильм с помощью БД, чтобы было всё корректно. Теперь изменил тип данных у сета в модели фильма, и всё стало десериализовывать как нужно.

2023-04-26 02:54 UTC, KosSpb commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                .genres(new LinkedHashSet<>(genresOfFilm(resultSet.getLong("film_id"))))
Исправлено.

2023-04-26 19:24 UTC, alexache approved these changes

2023-04-26 19:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LinkedHashSet<Genre> genres = new LinkedHashSet<>();
Лучше писать Set у типа поля

2023-04-26 21:02 UTC, KosSpb commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LinkedHashSet<Genre> genres = new LinkedHashSet<>();
Я помню про это правило, но если указать Set, то при десериализации получается фильм с HashSet вместо LinkedHashSet. Я пока не знаю как это настроить иначе, чем тип жёстко задать.

2023-04-26 21:41 UTC, merged